version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - transilogi-network

  trainer:
    build:
      context: .
      dockerfile: Dockerfile
      target: trainer
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - transilogi-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    depends_on:
      - db
      - trainer
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "8000:8000"
    networks:
      - transilogi-network

networks:
  transilogi-network:
    driver: bridge

volumes:
  mysql_data: